site_name: Python-Template
repo_url: https://github.com/dream-faster/python-template
repo_name: GitHub
site_author: Dream Faster
copyright: Dream Faster 2023
theme:
  name: material

nav:
    - Home: 'index.md'
    - Concepts:
      - Time Series Cross Validation: 'cross-validation.md'
      - Design: 'design.md'
      - Models: 'models.md'
      - Splitters: 'splitters.md'
    - Examples:
      - Simple ARIMA model: 'arima.py'
      - Date-time and Holiday features: 'datetime.py'
      - Ensembling models: 'ensembling.md'
      - Preprocess your data: 'preprocess.md'
      - Stacking models: 'stacking.md'
      - Tabular ML models: 'tabular.md'
      - Transform your target variable: 'transform-target.md'
    - 'reference.md'

plugins:
  - search
  - include-markdown
  - autorefs
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            separate_signature: true
            show_submodules: true
            show_signature_annotations: true
          import:
          - https://docs.python-requests.org/en/master/objects.inv